"""SQLAlchemy ORM models for thesis tracking and scoring."""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class Thesis(Base):
    """Persisted trade thesis generated by the analysis pipeline."""

    __tablename__ = "theses"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    ticker: Mapped[str] = mapped_column(String(10), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    flow_type: Mapped[str] = mapped_column(String(50), nullable=False)
    setup_classifications: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    spread_type: Mapped[str] = mapped_column(String(50), nullable=False)
    short_strike: Mapped[float] = mapped_column(Float, nullable=False)
    long_strike: Mapped[float] = mapped_column(Float, nullable=False)
    expiration_date: Mapped[date] = mapped_column(Date, nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    max_profit: Mapped[float] = mapped_column(Float, nullable=False)
    max_loss: Mapped[float] = mapped_column(Float, nullable=False)
    profit_target: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    state_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="active", index=True
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    closed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    daily_snapshots: Mapped[list["ThesisDailySnapshot"]] = relationship(
        back_populates="thesis", cascade="all, delete-orphan", lazy="selectin"
    )
    system_score: Mapped[Optional["SystemScore"]] = relationship(
        back_populates="thesis", cascade="all, delete-orphan", uselist=False, lazy="selectin"
    )
    user_score: Mapped[Optional["UserScore"]] = relationship(
        back_populates="thesis", cascade="all, delete-orphan", uselist=False, lazy="selectin"
    )


class ThesisDailySnapshot(Base):
    """Daily P&L and market snapshot for an active thesis."""

    __tablename__ = "thesis_daily_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    thesis_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("theses.id", ondelete="CASCADE"), nullable=False, index=True
    )
    snapshot_date: Mapped[date] = mapped_column(Date, nullable=False)
    underlying_close: Mapped[float] = mapped_column(Float, nullable=False)
    spread_mark: Mapped[float] = mapped_column(Float, nullable=False)
    pnl_dollars: Mapped[float] = mapped_column(Float, nullable=False)
    pnl_percent: Mapped[float] = mapped_column(Float, nullable=False)
    exit_condition_met: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)

    thesis: Mapped["Thesis"] = relationship(back_populates="daily_snapshots")


class SystemScore(Base):
    """Automated scoring of a thesis after it reaches expiration or close."""

    __tablename__ = "system_scores"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    thesis_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("theses.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    profitable_at_close_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    hit_profit_target: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    days_to_profit_target: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    max_favorable_excursion: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    max_adverse_excursion: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    final_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    thesis: Mapped["Thesis"] = relationship(back_populates="system_score")


class UserScore(Base):
    """Manual user scoring and review of a thesis."""

    __tablename__ = "user_scores"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    thesis_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("theses.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    direction_correct: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    structure_appropriate: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    timing_good: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    scored_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    thesis: Mapped["Thesis"] = relationship(back_populates="user_score")


class Watchlist(Base):
    """User watchlist of tickers to monitor."""

    __tablename__ = "watchlist"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    ticker: Mapped[str] = mapped_column(String(10), nullable=False, unique=True, index=True)
    added_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)


class ScreenerConfig(Base):
    """Saved screener filter configurations."""

    __tablename__ = "screener_configs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    filters: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
